### ISSUE TITLE
undefined identifiers

### ISSUE THREAD

**Issue by poeticAndroid** [Enalye/minuit#1]
Hey @Enalye !

I'd love to use your MIDI library as it seems to be the only one of its kind, but I can't seem to get it to work.. I tried the example code from the README, but it doesn't seem to recognize the words..

```D
import std.stdio;
import minuit;

void main(string[] args)
{
	MnOutputDevice[] outputDevices = mnFetchOutputs();

	writeln("List of output devices:");
	foreach (MnOutputDevice device; outputDevices)
	{
		writeln(device.name); 
	}

	MnInputDevice[] inputDevices = mnFetchInputs();

	writeln("List of input devices:");
	foreach (MnInputDevice device; inputDevices)
	{
		writeln(device.name);
	}
}
```

```
Performing "debug" build using C:\D\dmd2\windows\bin\dmd.exe for x86.
minuit 0.1.0: target for configuration "windows-build" is up to date.
hello_minuit ~master: building configuration "application"...
source\app.d(6,19): Error: undefined identifier MnOutputDevice
source\app.d(6,35): Error: undefined identifier mnFetchOutputs
source\app.d(14,18): Error: undefined identifier MnInputDevice
source\app.d(14,33): Error: undefined identifier mnFetchInputs
C:\D\dmd2\windows\bin\dmd.exe failed with exit code 1.
```

I'm running `DMD32 D Compiler v2.087.0` on Windows 10 Pro 64bit..

**Comment by Enalye** [comment]
Yeah sorry I changed names so the exemple is not correct and the version is outdated.
The library is still in early developpment so things are likely to be broken.
Instead of MnOutputDevice and MnInputDevice, it should be MnOutputPort and MnInputPort. I'm updating the readme right away.
I fixed some other things as well so you might want to dub upgrade to minuit v0.1.1

If things are still broken, please update on the issue !

**Comment by poeticAndroid** [comment]
Ah yes! now it works! :)

thanks! :D
